title: Yi DING's Homepage
author: Yi DING
description: > # this means to ignore newlines until "baseurl:"
  THis is Yi DING's Homepage
  
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - Research.md
 - MachineLearning.md

# Build settings
# markdown: kramdown    # Used originally
markdown: maruku        # Change to maruku on 12/15/17 to use mathjax
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  
google_analytics: UA-100040670-1